### ISSUE TITLE
Building doesn't work

### ISSUE THREAD

**Issue by Witherking25** [rofl0r/motor#8]
when i go to build a project, it immediately says it completed successfully, even though nothing actually happens.
![Screenshot from 2020-12-01 08-20-45](https://user-images.githubusercontent.com/39203202/100752470-459a5380-33ae-11eb-97c5-314a92e9622e.png)

**Comment by Witherking25** [comment]
to fix change 
```c++
	    execl(findprogram(GNUMAKE).c_str(), GNUMAKE,
		"-f", "Makefile.func",
		target.c_str(), 0);
```
to 
```c++
	    execlp("make", "make",
		"-f", "Makefile.func",
		target.c_str(), 0);
```
in 
src/executor/motorexecutor.cc
runmake function

**Comment by rofl0r** [comment]
> to fix change

congrats. can you open a PR with your change?
